# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6b13936cbca68562ebe0ce37b5b387a52e1c31afa0c81b0d5ee22652136491c2b4a055921a2c26f83aeb50d7f78cedcace66b273d74591ae6aeb71c055f275b

test:
  secret_key_base: da66633c67eaa0492ba4511a700bd140084efde9753da4f161a7ba471f7b8ff5510d0b59d8bdb096382ccad285e7e21a270241f7309d7f25da75bdd226040a5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
